### ISSUE TITLE
Some additions with Astro Mosaic

### ISSUE THREAD

**Issue by jabamula** [jarmoruuth/AstroMosaic#3]
I was struggling to get my own camera and telescope configurations. I didn't get the visibility diagrams. Then I noted that the default start object M79 isn't visible from my home. 
==> Could there be a way to decide the starting object by location, so it will be available in the visibility images?
==> Could the observatory location be available

Slooh currently in most cases allow missions during meridian change, my camera and telescope (Seestar) also do not need the meridian flip. 
==> Could the dotted red line with notion of invisibility be a choice for the user?
Great that Slooh Australia is now added to the choices!

**Comment by jarmoruuth** [comment]
> Could there be a way to decide the starting object by location, so it will be available in the visibility images?

I guess that could be done but calculating a good starting object by location sounds like be a complex task. Now the startup object matches to the version number.  In the Url you can also give your own startup target using the target option: https://ruuth.xyz/AstroMosaic.html?target=M31

> Could the observatory location be available

In the third row there is an Info button that shows the location among other things.  Or are you looking for something else?

> Could the dotted red line with notion of invisibility be a choice for the user?

I guess that meridian transit is a bit old from Slooh days. Maybe I should change it to a green dotted line and mark it as meridian? The user should know if something special is needed for meridian crossing or not. It could be an option too. But I have no idea how different telescopes behave there so maybe leaving some mark would still make sense. Already now the special time for meridian crossing can be set for each telescope.

**Comment by jabamula** [comment]
Thank you, the choice of the starting object (you have a clever choosing algorithm) and location are satisfactory available, those points are moot now. The program has so many nice details that I had omitted those altogether. 

A green dotted line is a good compromise, but it would be easier to understand, if it was shorter and the hover text 'not visible' is changed to 'meridian flip' or similar.

**Comment by jarmoruuth** [comment]
I now have a test version available at https://ruuth.xyz/test/AstroMosaic.html

It has two changes:
- Meridian crossing is marked separately with green dots. The displayed length is also shorter.
- Info display includes a Google maps link to show the telescope location.

**Comment by jabamula** [comment]
Hyvältä näyttää, tuo Googlen lisäys on myös hieno. A1 on hieman Siding Springsistä sivusta, ohessa selvennyskuva.
Kaukoputki on rakennuksessa, jonka katto on vedettävissä pois illan tullen, valkoisella ympäröity merkki. 

// Jari 

￼

**Comment by jarmoruuth** [comment]
Kuva ei aukea minulla. Ehkä laitat sen suoraan sähköpostiin?

jarmo
